import path from "node:path";
import tailwindcss from "@tailwindcss/vite";
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";

// Production bundler config. Test config is deliberately in a separate
// vitest.config.ts — see the header comment there.
export default defineConfig({
	// Tailwind v4 runs as a Vite plugin: no tailwind.config.js and no PostCSS
	// config exist in this repo. Utilities are generated by scanning source, and
	// design tokens live in the @theme block of src/index.css.
	plugins: [react(), tailwindcss()],

	resolve: {
		// Mirrors tsconfig.json `paths` and vitest.config.ts. Three places, keep in sync.
		alias: { "@": path.resolve(import.meta.dirname, "src") },
	},

	build: {
		// wrangler.jsonc points `assets.directory` at ./dist — changing this path
		// without changing wrangler.jsonc deploys a Worker with zero assets.
		outDir: "dist",
		emptyOutDir: true,
		rollupOptions: {
			output: {
				// Content-hashed filenames for everything. This is what lets
				// Cloudflare serve /assets/* with `immutable` long-lived caching:
				// a changed file gets a new URL, so no cache invalidation step is
				// needed on deploy. index.html itself stays unhashed and
				// short-cached, and is the only file that must be revalidated.
				entryFileNames: "assets/[name]-[hash].js",
				chunkFileNames: "assets/[name]-[hash].js",
				assetFileNames: "assets/[name]-[hash][extname]",
			},
		},
	},

	server: {
		port: 5173,
	},
});
