import path from "node:path";
import tailwindcss from "@tailwindcss/vite";
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";

// Production bundler config. Test config is deliberately in a separate
// vitest.config.ts — see the header comment there.
export default defineConfig({
	// Tailwind v4 runs as a Vite plugin: no tailwind.config.js and no PostCSS
	// config exist in this repo. Utilities are generated by scanning source, and
	// design tokens live in the @theme block of src/index.css.
	plugins: [react(), tailwindcss()],

	resolve: {
		// Mirrors tsconfig.json `paths` and vitest.config.ts. Three places, keep in sync.
		alias: { "@": path.resolve(import.meta.dirname, "src") },
	},

	build: {
		// wrangler.jsonc points `assets.directory` at ./dist — changing this path
		// without changing wrangler.jsonc deploys a Worker with zero assets.
		outDir: "dist",
		emptyOutDir: true,
		rollupOptions: {
			// Multi-page build: one HTML entry per route, each with its own static
			// <head>. This is what keeps SEO static (see CLAUDE.md) now that routes
			// have multiplied — a client-side router would render meta in JS, which
			// unfurlers never execute. Cloudflare's asset server resolves /product
			// to product/index.html, so no rewrite rule is needed.
			//
			// Adding a route means: an entry here, an HTML file, an entry module in
			// src/entries/, a <url> in public/sitemap.xml, and a canonical tag in
			// the new HTML. All five, or the page is invisible or misindexed.
			input: {
				main: path.resolve(import.meta.dirname, "index.html"),
				product: path.resolve(import.meta.dirname, "product/index.html"),
				company: path.resolve(import.meta.dirname, "company/index.html"),
				contact: path.resolve(import.meta.dirname, "contact/index.html"),
			},
			output: {
				// Content-hashed filenames for everything. This is what lets
				// Cloudflare serve /assets/* with `immutable` long-lived caching:
				// a changed file gets a new URL, so no cache invalidation step is
				// needed on deploy. index.html itself stays unhashed and
				// short-cached, and is the only file that must be revalidated.
				entryFileNames: "assets/[name]-[hash].js",
				chunkFileNames: "assets/[name]-[hash].js",
				assetFileNames: "assets/[name]-[hash][extname]",
			},
		},
	},

	server: {
		port: 5173,
	},
});
